from common import constants as con

#GENERAL
UTF_8='UTF-8'
FAKE_SIGNATURE= b'XHA334'
FAKE_BODY= b'body'
FAKE_SIGNATURE_STRING=FAKE_SIGNATURE.decode(UTF_8)

#COMMON MODULE
VALID_GH_SIGNATURE=con.PREFIX_GH+FAKE_SIGNATURE.decode(UTF_8)