from enum import Enum

#DB
DB_URL_KEY= 'DATABASE_URL'
DB_FALLBACK_FOLDER='instance'
DB_FALLBACK_FILE='adze.db'
TABLE_NAME_PROVIDERS='PROVIDERS'
TABLE_NAME_WEBHOOKS='WEBHOOKS'
TABLE_NAME_FORWARDS='FORWARDS'

#API
KEY_GH_SIGNATURE= 'X-Hub-Signature-256'
KEY_GH_DELIVERY='X-GitHub-Delivery'
KEY_GH_EVENT='X-GitHub-Event'
PREFIX_GH='sha256='
DIGEST_MOD_GH= 'SHA256'
WEBHOOK_SECRET_KEY_GH='GITHUB_WEBHOOK_SECRET'

#ERRORS AND API INFOS
ERROR_INVALID_CREDENTIALS='Invalid credentials'
ERROR_KEY_NOT_FOUND='Key not found'
ERROR_FAILED_PARSE='Failed to parse arrived package.'
ERROR_UNAUTHORIZED='UNAUTHORIZED'
INFO_OK='OK'
ERROR_STORAGE='STORAGE ERROR'

#NORMA
NORM_KEY_PROVIDER = "provider"
PROVIDER_GH='github'
PROVIDER_TWILIO='twilio'
PROVIDER_STRIPE='stripe'
NORM_KEY_EVENT_TYPE = "event_type"
NORM_KEY_DELIVERY_ID = "delivery_id"
NORM_KEY_TIMESTAMP = "timestamp"
NORM_KEY_RAW_PAYLOAD = "raw_payload"
PROVIDERS_ALL=PROVIDER_GH, PROVIDER_TWILIO, PROVIDER_STRIPE

#ENUMS
class HandlerErrors(Enum):
    OK = INFO_OK
    UNAUTHORIZED = ERROR_UNAUTHORIZED
    ERROR_STORAGE = ERROR_STORAGE